### ISSUE TITLE
Like to know the update

### ISSUE THREAD

**Issue by 1ckola** [Arlindog/RxIGListKit#2]
Hi,
RxIGListKit still work in progress?

**Comment by JohnKuan** [comment]
@yuzushioh 
Hi, thanks for starting this extension from IGListKit! Similar to @1ckola, I would like to know if you plan to continue on this repo.

**Comment by Dfmarulanda** [comment]
@yuzushioh could you transfer me the ownership? I'll keep developing.

**Comment by yuzushioh** [comment]
@Dfmarulanda sure. Give me one sec

**Comment by Arlindog** [comment]
If the ownership has not been transferred yet, Is there anyway that I can take ownership of the repo so I can continue the development. It seems to have halted for a loooong time now and I would like to keep it going.

**Comment by yuzushioh** [comment]
@Arlindog yes sure. I can give you the ownership

**Comment by yuzushioh** [comment]
@Arlindog `Arlindog/RxIGListKit already exists` can you delete your repository or at least rename yours?

**Comment by Arlindog** [comment]
Its deleted. You should be good to transfer now.

**Comment by Arlindog** [comment]
@yuzushioh Just pining you one more time about the transfer when you have the time.

**Comment by yuzushioh** [comment]
@Arlindog done ✅

**Comment by Arlindog** [comment]
thank you!
